import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/common/header/Header";
import Footer from "./component/common/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const footerItem = [
  {
    title: "Company",
    child: [
      {
        name: "About us",
        path: "/about",
      },
      {
        name: "Careers",
        path: "/careers",
      },
      {
        name: "Blog",
        path: "/blogs",
      },
    ],
  },
  {
    title: "Services",
    child: [
      {
        name: "Enterprise software",
        path: "/enterprise_software",
      },
      {
        name: "Hire Dedicated Developers",
        path: "/hire_dedicated_developers",
      },
      {
        name: "Mobile App",
        path: "/mobile_apps",
      },
    ],
  },
  {
    title: "Hire Developer Team",
    child: [
      {
        name: "AngularJS Developers",
        path: "/angularjs_developers",
      },
      {
        name: "Android App Developers",
        path: "/android_app_developers",
      },
      {
        name: "AI & ML Developers",
        path: "/ai_ml_developers",
      },
      {
        name: "ASP.NET Developers",
        path: "/asp_net_developers",
      },
    ],
  },
  {
    title: "",
    child: [
      {
        name: "Java Developers",
        path: "/java_developers",
      },
      {
        name: "NodeJS Web Developers",
        path: "/nodejs_web_developers",
      },
      {
        name: "PHP Developers",
        path: "/php_developers",
      },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* header section */}
        <Header />
        {/* main content */}
        {children}
        {/* Footer section */}
        <Footer props={footerItem} />
      </body>
    </html>
  );
}
